name: Live Stream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install ffmpeg -y

      - name: Start Stream
        run: |
          ffmpeg -re -stream_loop -1 \
          -i "https://drive.google.com/uc?export=download&id=1k_gF6NNEqDFAOTyCjR9gNq5NWUPmIkxu" \
          -i "https://drive.google.com/uc?export=download&id=1Ie7lS-_SagxR58qcJrwN9MGirkCRq0df" \
          -c:v copy \
          -c:a aac -b:a 128k \
          -f flv rtmp://a.rtmp.youtube.com/live2/YOUR_STREAM_KEY
